pull_request_rules:
  - name: Automatic merge on CI success and review
    conditions:
    - or:
      - "#approved-reviews-by>=1"
      - approved-reviews-by=Xunzhuo
      - approved-reviews-by=Xunzhuo
    actions:
      merge:
        method: squash
  - name: Say hello to contributors
    conditions:
      - -draft
    actions:
      comment:
        message: |
           Welcome to the [Async](https://github.com/merbridge/merbridge) OpenSource Project!👏

           We're delighted to have you onboard 💘
           
           Thanks for your contribution, any ideas, issues, PRs are welcomed! ⚡️
